# Generated by Django 4.2.30 on 2026-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='GPS latitude of the detected pothole')),
                ('longitude', models.FloatField(help_text='GPS longitude of the detected pothole')),
                ('confidence', models.FloatField(help_text='Model Confidence score(0.0 to 1.0)')),
                ('image', models.ImageField(help_text='Uploaded image with pothole', upload_to='pothole_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Detection timestamp')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('repaired', 'Repaired')], default='pending', help_text='Repair status of the pothole', max_length=10)),
            ],
            options={
                'verbose_name': 'Pothole',
                'verbose_name_plural': 'Potholes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
